# Generated by Django 5.2.7 on 2025-12-06 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_order_payment_method_order_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('smartphones', 'Smartphones'), ('laptops', 'Laptops'), ('headphones', 'Headphones'), ('smart watches', 'Smart Watches'), ("men's clothing", "Men's Clothing"), ("women's clothing", "Women's Clothing"), ('shoes', 'Shoes'), ('accessories', 'Accessories'), ('refrigerators', 'Refrigerators'), ('washing machines', 'Washing Machines'), ('microwaves', 'Microwaves'), ('air conditioners', 'Air Conditioners'), ('makeup', 'Makeup'), ('skincare', 'Skincare'), ('haircare', 'Haircare'), ('fragrances', 'Fragrances')], max_length=50),
        ),
    ]
